export const REGIONAL_COUNCIL = {
  DOCTOR: 'CRM',
  NURSE: 'COREN',
  NUTRITIONIST: 'CFN',
  SPEECH_THERAPIST: 'CREFONO',
  PHYSIOTHERAPIST: 'CREFITO',
  NURSE_TECH: 'COREN',
  PSYCHOLOGIST: 'CRP'
};
