export const ROLES = {
  MEDIC: 'DOCTOR',
  NURSE: 'NURSE',
  NUTRITIONIST: 'NUTRITIONIST',
  SPEECH_THERAPIST: 'SPEECH_THERAPIST',
  PHYSIOTHERAPIST: 'PHYSIOTHERAPIST',
  NURSE_TECH: 'NURSE_TECH',
  PSYCHOLOGIST: 'PSYCHOLOGIST'
};
